[package]
name = "code_infra"
version = "0.1.0"
edition = "2021"

[dependencies]
code_domain = { path = "../code_domain" }
common_domain = { path = "../../common/common_domain" }
itertools = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
regex = { workspace = true }
tokio = { workspace = true }
paste = { workspace = true }

[features]
dart = []
flutter = []
