[package]
name = "request_avatar_upload_v1"
version = "0.1.0"
edition = "2021"

[dependencies]
bucket_domain = { path = "../../../../feature/bucket/bucket_domain" }
bucket_infra = { path = "../../../../feature/bucket/bucket_infra" }
common_api = { path = "../../../common_api", features = ["lambda"] }
common_domain = { path = "../../../../feature/common/common_domain" }
futures = { workspace = true }
lambda_http = { workspace = true, features = ["apigw_rest"] }
profile_infra = { path = "../../../../feature/profile/profile_infra" }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true }
use_case = { path = "../../../../use_case", features = [
  "request_avatar_upload",
] }
