version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/infra/base"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/infra/dev"
    schedule:
      interval: "weekly"
