[workspace]
members = [
  "backend/api/container/*",
  "backend/api/common_api",
  "backend/api/lambda/*",
  "backend/feature/common/*",
  "backend/feature/code/*",
  "backend/use_case",
  "xtask",
]

[workspace.dependencies]
actix-web = { version = "4" }
clap = { version = "3.2.17" }
futures = "0.3"
fs_extra = { version = "1.2.0" }
lambda_http = { version = "0.6", default-features = false }
lambda_runtime = { version = "0.6" }
nanoid = { version = "0.4" }
openssl = { version = "0.10", features = ["vendored"] }
reqwest = { version = "0.11.12" }
serde = { version = "1.0" }
serde_json = { version = "1.0" }
tokio = { version = "1" }
toml = { version = "0.5.9" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", default-features = false }
walkdir = { version = "2.3.2" }
zip = { version = "0.6.2", default-features = false }
