[workspace]
members = [
  "backend/api/common_api",
  "backend/api/container/*",
  "backend/api/lambda/*",
  "backend/feature/code/*",
  "backend/feature/common/*",
  "backend/use_case",
  "xtask",
]

[workspace.dependencies]
axum = { version = "0.5" }
clap = { version = "3.2" }
futures = { version = "0.3" }
itertools = { version = "0.10" }
lambda_http = { version = "0.6", default-features = false }
lambda_runtime = { version = "0.6" }
lazy_static = { version = "1.4" }
log = { version = "0.4" }
mockall = { version = "0.11" }
sha3 = { version = "0.10" }
nanoid = { version = "0.4" }
serde = { version = "1.0" }
serde_json = { version = "1.0" }
tokio = { version = "1.21" }
tokio-util = { version = "0.7" }
toml = { version = "0.5" }
tower-http = { version = "0.3" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
regex = { version = "1.6" }
paste = { version = "1.0" }
walkdir = { version = "2.3" }
zip = { version = "0.6", default-features = false }
