FROM rust:1.64 as builder

ARG LANG=full
WORKDIR /app
COPY . .
RUN cargo build --release -p code_service --no-default-features -F flutter


FROM cirrusci/flutter:latest

WORKDIR /app
RUN flutter doctor
COPY --from=builder /app/target/release/code_service .
CMD [ "./code_service" ]
