FROM rust:1.64 as builder

ARG LANG=full
WORKDIR /app
COPY . .
RUN cargo build --release -p code_service --no-default-features -F full


FROM cirrusci/flutter:latest

RUN mkdir /app
COPY --from=builder /app/target/release/code_service /app
RUN flutter doctor
CMD [ "/app/code_service" ]

