FROM rust:1.65 as builder

WORKDIR /app
RUN rustup update nightly
COPY . .
RUN cargo +nightly build -Z sparse-registry --release -p code_service --no-default-features -F dart


FROM dart:latest

WORKDIR /app
COPY --from=builder /app/target/release/code_service .
CMD [ "./code_service" ]
