[package]
name = "get_fake_tasks_to_load"
version = "0.1.0"
edition = "2021"

[dependencies]
common_api = { path = "../../../common_api", features = ["lambda"] }
fake = { workspace = true }
lambda_http = { workspace = true, features = ["apigw_rest"] }
load_tasks_v1 = { path = "../load_tasks_v1", features = ["fake_dto"] }
tokio = { workspace = true }
