[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
sha3 = { workspace = true }
toml = { workspace = true }
zip = { workspace = true }
