[package]
name = "on_modifications_batch"
version = "0.1.0"
edition = "2021"

[dependencies]
aws_lambda_events = { workspace = true, features = ["sqs"] }
common_api = { path = "../../../common_api", features = ["lambda"] }
common_domain = { path = "../../../../feature/common/domain" }
futures = { workspace = true }
lambda_runtime = { workspace = true }
task_domain = { path = "../../../../feature/task/domain" }
task_infra = { path = "../../../../feature/task/infra", features = ["dto"] }
tokio = { workspace = true }
use_case = { path = "../../../../use_case", features = [
  "on_modification_batch",
] }
