[package]
name = "with_id"
version = "0.1.0"
edition = "2021"

[dependencies]
darling = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[lib]
proc-macro = true
