[package]
name = "bucket_domain"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
common_domain = { path = "../../common/common_domain" }
mockall = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["mockall"]
