[package]
name = "load_tasks_v1"
version = "0.1.0"
edition = "2021"

[dependencies]
common_api = { path = "../../../common_api", features = ["lambda"] }
common_domain = { path = "../../../../feature/common/domain" }
fake = { workspace = true, features = ["derive", "uuid"], optional = true }
futures = { workspace = true }
lambda_http = { workspace = true, features = ["apigw_rest"] }
rand = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
task_domain = { path = "../../../../feature/task/domain" }
task_infra = { path = "../../../../feature/task/infra" }
tokio = { workspace = true }
use_case = { path = "../../../../use_case", features = ["load_tasks"] }
uuid = { workspace = true, features = ["serde", "v4"] }
validator = { workspace = true, features = ["derive"] }

[lib]
name = "load_tasks_v1"
path = "src/lib.rs"

[[bin]]
test = false
name = "load_tasks_v1"
path = "src/main.rs"

[features]
default = []
fake_dto = ["fake", "rand"]

[package.metadata.cargo-machete]
ignored = ["rand"]
