[package]
name = "load_tasks_v1"
version = "0.1.0"
edition = "2021"

[dependencies]
common_api = { path = "../../../common_api", features = ["lambda"] }
lambda_http = { workspace = true, features = ["apigw_rest"] }
tokio = { workspace = true }
use_case = { path = "../../../../use_case", features = ["load_tasks"] }

[lib]
name = "load_tasks_v1"
path = "src/lib.rs"

[[bin]]
name = "load_tasks_v1"
path = "src/main.rs"
