[package]
name = "common_api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { workspace = true }
common_domain = { path = "../../feature/common/common_domain" }
serde = { workspace = true, features = ["derive"] }

[features]
default = []
