[package]
name = "profile_infra"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-dynamodb = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
common_domain = { path = "../../common/common_domain" }
common_infra = { path = "../../common/common_infra", features = ["dynamodb"] }
profile_domain = { path = "../profile_domain" }
serde = { workspace = true }
serde_dynamo = { workspace = true, features = ["aws-sdk-dynamodb+0_21"] }
