[package]
name = "user_infra"
version = "0.1.0"
edition = "2021"

[dependencies]
common_domain = { path = "../../common/domain" }
common_infra = { path = "../../common/infra" }
lazy_static = { workspace = true }
