[package]
name = "content_infra"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-dynamodb = { workspace = true }
aws-sdk-sqs = { workspace = true }
chrono = { workspace = true }
common_domain = { path = "../../common/domain" }
common_infra = { path = "../../common/infra", features = ["sqs", "dynamodb"] }
content_domain = { path = "../../content/domain" }
lazy_static = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_dynamo = { workspace = true }
serde_json = { workspace = true }

[features]
dto = []
