name: Deploy - uat

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  upload-uat:
    runs-on: ubuntu-latest
    name: Upload uat
    steps: 
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            target/
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
          key: ${{ runner.os }}-cargo-build

      - name: Install latest rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: Install cross
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cross

      - name: Build lambdas
        uses: actions-rs/cargo@v1
        with:
          command: xtask
          args: build-lambdas --use-cross --target aarch64-unknown-linux-gnu

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Init terraform
        working-directory: ./infra/uat
        run: terraform init

      - name: Deploy
        working-directory: ./infra/uat
        env:
          TF_VAR_app_api_key: ${{ secrets.UAT_APP_API_KEY }}
          TF_VAR_moderator_api_key: ${{ secrets.UAT_MODERATOR_API_KEY }}
        run: terraform apply -auto-approve
